import { GuitarSpecs } from '../types/gear';

export const createEmptyGuitarSpecs = (): GuitarSpecs => ({
  overview: {
    manufacturer: '',
    model: '',
    bodySizeShape: '',
    series: '',
    buildType: '',
    topMaterial: '',
    bodyMaterial: '',
    scaleLength: '',
    nutWidth: '',
    neckShapeProfile: '',
    neckTypeConstruction: '',
    pickupConfiguration: '',
    countryOfOrigin: '',
    serialNumber: '',
  },
  top: {
    color: '',
    finish: '',
    binding: '',
    inlayMaterial: '',
    detail: '',
    bridgeStyle: '',
    rosette: '',
    bridgeStringSpacing: '',
    bridgeMaterial: '',
    bridgePinMaterial: '',
    bridgePinDots: '',
    saddle: '',
    saddleRadius: '',
  },
  body: {
    design: {
      color: '',
      finish: '',
      binding: '',
      backPurfling: '',
      backInlayMaterial: '',
      backDetail: '',
      sideDetail: '',
      sideInlayMaterial: '',
      endpiece: '',
      endpieceInlay: '',
      heelcap: '',
    },
    bracing: {
      bodyBracing: '',
      bracingPattern: '',
      braceShape: '',
      braceMaterial: '',
      braceSize: '',
    },
    dimensions: {
      bodyDepth: '',
      upperBoutWidth: '',
      upperBoutDepth: '',
      lowerBoutWidth: '',
      lowerBoutDepth: '',
    },
  },
  neckAndHeadstock: {
    neck: {
      taper: '',
      material: '',
      color: '',
      finish: '',
      binding: '',
      numberOfFrets: '',
      joinsBodyAt: '',
      sideDots: '',
      trussRodType: '',
      nutMaterial: '',
    },
    fingerboard: {
      material: '',
      radius: '',
      widthAt12thFret: '',
      inlayStyle: '',
      inlayMaterial: '',
      bindingMaterial: '',
      rolledEdges: '',
      fretSize: '',
      fretMarkerStyle: '',
    },
    headstock: {
      shape: '',
      plateMaterial: '',
      logoStyle: '',
      bindingMaterial: '',
      detail: '',
    },
  },
  electronics: {
    acousticPickup: '',
    numberOfPickups: '',
    bridgePickup: '',
    middlePickup: '',
    neckPickup: '',
    pickupColor: '',
    controls: '',
    pickupSwitching: '',
    outputType: '',
    specialElectronics: '',
  },
  hardware: {
    bridge: '',
    finish: '',
    tuningMachines: '',
    tuningMachineKnobs: '',
    tailpiece: '',
    pickguard: '',
    pickguardInlay: '',
    controlKnobs: '',
    switchTip: '',
    neckPlate: '',
    strapButtons: '',
  },
  miscellaneous: {
    pleked: false,
    label: '',
    case: '',
    recommendedStrings: '',
    weight: '',
    orientation: '',
    comments: '',
  }
}); 